spring:
  application:
    name: auth-service
  config:
    import: optional:configserver:config-server
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server

    #function:
     # defination: userCreatedOutput
    stream:
      #kafka:
       # binder:
        #  brokers: 192.168.1.8
         # defaultBrokerPort: 9092
      bindings:
        userCreatedOutput-out-0:
          destination: userCreatedOutput
          #binder: kafka
          #group: group
          #consumer:
          #  concurrency: 10
          #  max-attempts: 3

  datasource:
    url: jdbc:postgresql://postgres_container1:5432/testdb
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

    hibernate:
      ddl-auto: update
eureka:
  client:
    service-url:
      default-zone: http://discoveryservice:8761/eureka/

jwt:
  secret: BvPHGM8C0ia4uOuxxqPD5DTbWC9F9TWvPStp3pb7ARo0oK2mJ3pd3YG4lxA9i8bj6OTbadwezxgeEByY
  expiration: 86400