spring:
  application:
    name: auth-service
  config:
    import: optional:config-server/
    cloud:
      bootstrap:
        enabled: true
server:
  port: 9100

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka


