spring:
  application:
    name: common-service
  config:
    import: optional:config-server/
    cloud:
      bootstrap:
        enabled: true

server:
  port: 9200

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka