server:
  port: 8014

spring.redis:
    host: localhost
    port: 6379
    client-type: lettuce

---
spring.config.activate.on-profile: docker
spring.redis:
  host: redis
  port: 6379
  client-type: lettuce
