spring:
  application:
    name: course-service
  config:
    import: optional:config-server/
  cloud:
    bootstrap:
      enabled: true


logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.assignment: DEBUG
