spring:
  application:
    name: student-service
  config:
    import: optional:configserver:config-server
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server

    stream:
      kafka:
        binder:
          brokers: kafka
      #function:
       # defination: getNewlyCreatedUser
      bindings:
        getNewlyCreatedUser-in-0:
          destination: userCreatedOutput
          #binder: kafka
          group: mygroup
        studentCreatedOutput-out-0:
          destination: studentCreatedOutput
  data:
    mongodb:
      host: localhost
      port: 27017
      database: student_db

eureka:
  client:
    service-url:
      default-zone: http://discoveryservice:8761/eureka/

