version: '3.8'
services:
  postgres_container1:
    restart: always
    image: "postgres:latest" # use latest official postgres version
    env_file:
      - database.env # configure postgres
    ports:
      - "5432:5432"
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
    networks:
      - backend
volumes:
  database-data: # named volumes can be managed easier using docker-compose

networks:
  backend:
    driver: bridge