server.port: 8012
spring.application.name: course
logging:
  level:
    root: INFO
    io.javatab.microservices: DEBUG

app.eureka-server: localhost

eureka:
  client:
    serviceUrl:
      defaultZone: http://${app.eureka-server}:8761/eureka/
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5

---
spring.config.activate.on-profile: docker
server.port: 8080
app.eureka-server: eureka
spring.data.mongodb.host: mongodb