spring:
  application:
    name: eureka-server
  config:
    import: optional:config-server/
  cloud:
    bootstrap:
      enabled: true

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
