spring:
  application:
    name: config-server
  profiles:
    active:
      - git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/nasruddin/config.git
      discovery:
        enabled: true
        #service-id: config-server

server:
  port: 8071

#Enable all Spring Boot Actuator endpoints.
management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    service-url:
      default-zone: http://discoveryservice:8761/eureka/